name: Generate Snake

on:
  schedule: 
    - cron: "0 0 * * *"  # Runs every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v2.0.0  # Specify the latest stable version
        with:
          github_user_name: z-reger  # Replace with your GitHub username
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Push generated Snake
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Generated Snake"
          git push
